config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :labels
  get 'topics/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  get  '/favorites/index'
  get 'topics/search'
  get 'submits/index'
  post '/favorites', to: 'favorites#create'
  post '/login',   to: 'sessions#create'
  post '/submits', to: 'submits#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/favorites', to: 'favorites#destroy'
  delete '/submits', to: 'submits#destroy'
  
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :topics
  resources :comments, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :test_sessions, only: :create

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title>About</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      is a <a href="https://railstutorial.jp/#ebook">book</a> and
      <a href="https://railstutorial.jp/screencast">screencast</a>
      to teach web development with
      <a href="https://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCMENT html>
<html>
  <head>
    <title>Contact</title>
  </head>
  <body>
    <h1>Contact</h1>
    <p>
      Contact the Ruby on Rails Tutorial about the sample app at the
      <a href="https://railstutorial.jp/contact">contact page</a>.
    </p>
    
    
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title>Help</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="https://railstutorial.jp/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="https://railstutorial.jp/#ebook">
      <em>Ruby on Rails Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
  <div class="text-center" id="home">
    <div class="container">
      <div class="row">
        <div class="theme bg-white col-10 mx-auto mx-md-0 col-lg-6">
          <h1>ほしいアイデアが<br>きっとある。</h1>
          <p class="lead">時間がない…そんな先生たちへ。<br>アイデアを共有して助け合おう。</p>
          <%= link_to "登録して始める", signup_path , class: "btn btn-lg btn-info" %>
          <%= link_to "テストユーザーはこちら", test_sessions_path, method: :post , class: "btn btn-lg btn-warning mt-2" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="col-md-12 my-5">
      <h2 class="sentence_info">IDEA BOXの特長</h2>
      <hr />
      </div>
    </div>
  <div class="py-1" >
    <div class="container">
      <div class="row">
        <div class="string col-md-8">
          <h3 class="mb-3 text-whit">写真、動画の投稿</h3>
          <div class="blockquote text-muted">
            <p class="mb-0">板書や掲示物など、を他の先生方に共有しましょう！<br>
                            あなたの実践したことが誰かのヒントにきっとなります！<br>
                            1つの投稿で複数枚投稿できます。</p>
            <div class="blockquote-footer">※個人情報が特定されてしまう投稿はご遠慮ください</div>
          </div>
        </div>
        <div class="slide col-md-4">
          <%= image_tag 'home_image.png', class: "img-fluid d-block mx-auto" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="py-1" >
    <div class="container">
      <div class="row">
        <div class="string col-md-8">
          <h3 class="mb-3 text-whit">ワークシートや指導案の添付</h3>
          <div class="blockquote text-muted">
            <p class="mb-0">作成した学習カードなどをワードやエクセル形式で共有。<br>
                            簡単に保存できるので児童生徒の実態に合わせてアレンジできます。</p>
          </div>
        </div>
        <div class="col-md-4">
           <%= image_tag 'homeimage1.jpg', class: "img-fluid d-block mx-auto" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="py-1" >
    <div class="container">
      <div class="row">
        <div class="string col-md-8">
          <h3 class="mb-3 text-whit">ニックネームで簡単登録！</h3>
          <div class="blockquote text-muted">
            <p class="mb-0">面倒な本人確認も必要ありません！<br>
                            メールアドレスや勤務地、担当学年を入力するだけで<br>
                            簡単に登録できます。</p>
          </div>
        </div>
        <div class="col-md-4">
           <%= image_tag 'home_image3.png', class: "img-fluid d-block mx-auto" %>
        </div>
      </div>
    </div>
  </div>
     
    </div>
  
 <script>
 
  let bgWhite = document.getElementsByClassName("theme");
  window.addEventListener('load', (event) => {
    console.log(bgWhite);
    bgWhite[0].classList.add("bg-white-after");
  });
  
  
 
  function showElementAnimation() {
    var element = document.getElementsByClassName('img-fluid');
    if(!element) return;
  
    var showTiming = window.innerHeight > 768 ? 200 : 40;// 要素が出てくるタイミングはここで調整
    var scrollY = window.pageYOffset;
    var windowH = window.innerHeight;
    
    for (var i=0;i<element.length;i++) {
      var elemClientRect = element[i].getBoundingClientRect();
      var elemY = scrollY + elemClientRect.top;
      if(scrollY + windowH - showTiming > elemY) {
        element[i].classList.add('is-show');
      } else if (scrollY + windowH < elemY) {
        // 上にスクロールして再度非表示にする場合はこちらを記述
        element[i].classList.remove('is-show');
      }
    }
  }
  showElementAnimation();
  window.addEventListener('scroll', showElementAnimation);
  
 </script>

 