config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :labels
  get 'topics/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  get  '/favorites/index'
  get 'topics/search'
  get 'submits/index'
  post '/favorites', to: 'favorites#create'
  post '/login',   to: 'sessions#create'
  post '/submits', to: 'submits#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/favorites', to: 'favorites#destroy'
  delete '/submits', to: 'submits#destroy'
  
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :topics
  resources :comments, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :test_sessions, only: :create

end

app/models/submit.rb
class Submit < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :logged_in_user
  
  def index
    @submit_topics = current_user.submit_topics
  end

  def create
    Submit.create(user_id: current_user.id, topic_id: params[:topic_id])
    @topic = Topic.find(params[:topic_id])
    # submit = Submit.new
    # submit.user_id = current_user.id
    # submit.topic_id = params[:topic_id]

    # if submit.save
    #   redirect_to topics_path
    #   flash[:success] = 'マイフォルダに保存しました'
    # else
    #   redirect_to 
    #   flash[:danger]  = '保存に失敗しました'
    # end
  end
  
 def destroy
   if params[:button] == "garbage"
       #submit_indexのごみ箱のボタンを実行したとき
       Submit.find_by(user_id: current_user.id, topic_id: params[:topic_id]).destroy
       @topic = Topic.find(params[:topic_id])
       flash[:success] = "マイフォルダから削除しました"
       redirect_to submits_index_path
   else
       Submit.find_by(user_id: current_user.id, topic_id: params[:topic_id]).destroy
       @topic = Topic.find(params[:topic_id])
       #lash[:success] = "マイフォルダから削除しました"
       #redirect_to submits_index_path
   end
 end
 
  private
   #ログイン済みユーザーかどうかを確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
  
    def user_params
      params.require(:user).permit(:name, :email, :user_area, :user_job,
                                   :school_year, :avatar,
                                   :password,
                                   :password_confirmation)
    end

end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/views/submits/_submit.html.erb
<% if !topic.submit_users.include?(current_user) %>
   <%= link_to submits_path(topic_id: topic.id), method: :post, remote: true do %>
     <i class="far fa-bookmark fa-2x mt-2 ml-2 mb-2" style="color: black;"></i>
   <% end %>
 <% else %>
   <%= link_to submits_path(topic_id: topic.id), method: :delete, remote: true do %>
     <i class="fas fa-bookmark fa-2x mt-2 ml-2 mb-2" style="color: royalblue;"></i>
  <% end %>
<% end %>
<%= topic.submit_users.count %>

app/views/submits/create.js.erb
$('#submits_buttons_<%= @topic.id %>').html("<%= j(render partial: 'submits/submit', locals: {topic: @topic}) %>");

app/views/submits/destroy.js.erb
$('#submits_buttons_<%= @topic.id %>').html("<%= j(render partial: 'submits/submit', locals: {topic: @topic}) %>");

app/views/submits/index.html.erb
<h2>マイフォルダ</h2>

  
  <div class="container">
    <!--9行目のeach文の外で書かないとコードが複雑になってしまう-->
     <% if @submit_topics.count == 0 %>
        <h4>マイフォルダは空です</h4>
      <% end %>
     <% @submit_topics.each do |topic| %>
　　<div class="border" style="padding:10px;">
    <div class="row">
      <div class="col-md-3">
        <%= link_to topic_path(id: topic.id), method: :get do %>
            <% if topic.images.count > 0 %>
               <% if topic.images[0].file.content_type.include?('image/') %>
                 <%= image_tag topic.images[0].url, class: "img-list" %>
               <% else %>
                 <div class="img-list">
                   <%= video_tag topic.images[0].url, class: "img-list", poster_skip_pipeline: true %>
                   <%= image_tag "movie_video_icon.png", class: "img-list", style: "position: absolute; left:0;" %>
                 </div>
               <% end %>
            <% else %>
              <%= image_tag "no_image.png", class: "img-list" %>
            <% end %>
        <% end %>
        </div>
          <div class="col-md-7">
            <% if topic.user.avatar? %>
              <%= image_tag user.avatar.url, size:"40x40" %>
            <% else %>
              <%= image_tag "noavatar.png", size:"40x40" %>
            <% end %>
            <%= link_to topic.user.name, topic.user %>
          <p>
            <% topic.labels.each do |label| %>
              <i class="fas fa-tag"></i><%= label.name %>
            <% end %>
          </p>
          <p class="topic-text">
            <%= topic.description.truncate(67, omission: '...') %>
          </p>
          </div>
          <div class="col-md-2 text-right">
            <!--garbageというparamsを与えてdestroyアクション内で処理を条件分岐させる-->
            <%= link_to submits_path(topic_id: topic.id, button: "garbage"), method: :delete do %>
              <i class="far fa-trash-alt fa-2x"></i>
            <% end %>
          </div>
        </div>
      </div>
   <% end %>
  </div>