config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :labels
  get 'topics/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  get  '/favorites/index'
  get 'topics/search'
  get 'submits/index'
  post '/favorites', to: 'favorites#create'
  post '/login',   to: 'sessions#create'
  post '/submits', to: 'submits#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/favorites', to: 'favorites#destroy'
  delete '/submits', to: 'submits#destroy'
  
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :topics
  resources :comments, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :test_sessions, only: :create

end

app/views/layouts/_footer.html.erb
<!--<footer class="footer">-->
<!--  <small>-->
<!--    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>-->
<!--    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>-->
<!--  </small>-->
<!--  <nav>-->
<!--    <ul>-->
<!--      <li><%= link_to "About",   about_path %></li>-->
<!--      <li><%= link_to "Contact", contact_path %></li>-->
<!--      <li><%= link_to "helf",    help_path %></li>-->
<!--      <li><a href="https://news.railstutorial.org/">News</a></li>-->
<!--    </ul>-->
<!--  </nav>-->
<!--</footer>-->

app/views/layouts/_form.html.erb
 
<%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, '名前　*必須' %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <% if action_name == 'new' %>
        <%= f.label :email, 'メールアドレス　*必須' %>
        <%= f.email_field :email, class: 'form-control' %>
      <% end %>
      
      <%= f.label :user_area, '勤務地　*必須' %>
      <%= f.select :user_area, User.user_areas { |p| [ p.name, p.id ] }, {prompt: '選択してください'}, class: 'form-control' %>

      <%= f.label :user_job, '役職（任意）' %>
      <%= f.select :user_job, User.user_jobs { |p| [ p.name, p.id ] }, {prompt: '選択してください'}, class: 'form-control' %>
      
      <%= f.label :school_year, '担当学年　*必須' %>
      <%= f.select :school_year, User.school_years  { |p| [ p.name, p.id ] }, {prompt: '選択してください'}, class: 'form-control' %>
      
      <% if action_name == 'new' %>
        <%= f.label :password, 'パスワード *必須' %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :password_confirmation, "パスワード（確認用）" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      <% end %>
      
      <%= f.label :profile, "自己紹介" %>
      <%= f.text_area :profile, class: 'form-control' %>
      <label>アイコン</label>
      <div class="gravatar_edit">
      <% if @user.avatar? %>
        <%= image_tag @user.avatar.url, class: "rounded-circle", size: "200x200" %>
      <% else %>
        <%= image_tag "noavatar.png", class: "rounded-circle", size: "200x200"%>
      <% end %>
 　　 <%= f.file_field :avatar, id: "file-sample" %>
    　</div>
    　<img class="rounded-circle" id="file-preview" width="200" height="200" style="border:none;" >
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
    
    <script>
    document.getElementById('file-sample').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('file-preview');
    img.src = blobUrl;
});
</script>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-dark bg-dark fixed-top">
    <div class="nav navbar-nav navbar-left">
       <%= link_to "IDEA BOX", root_path, id: "logo", method: :get %>
    </div>
      <ul class="nav list-group mr-auto list-group-horizontal">
        <li class="inline-block ml-3">
          <%= link_to  root_path, method: :get do %>
            <i class="fas fa-home"></i>
          <% end %>
        </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle ml-3" data-toggle="dropdown">
                 <i class="fas fa-camera"></i><b class="caret"></b>
            </a>
            <ul class="dropdown-menu bg-dark">
              <li class="ml-2">
                <%= link_to new_topic_path, method: :get do %>
                  <i class="fas fa-plus"></i>　新規投稿
                <% end %>
              </li>
              <li class="ml-2">
                <%= link_to  topics_path, method: :get do %>
                  <i class="fas fa-images"></i>　投稿一覧
                <% end %>
              </li>
            </ul>
          </li>
          
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle ml-3" data-toggle="dropdown">
                <i class="fas fa-user"></i><b class="caret"></b>
            </a>
            <ul class="dropdown-menu bg-dark">
              <li class="ml-2">
                <%= link_to current_user, method: :get do %>
                  <i class="fas fa-portrait"></i>　マイページ
                <% end %>
              </li>
              <li class="ml-2">
                <%= link_to users_path, method: :get do %>
                  <i class="fas fa-users"></i>　ユーザー一覧
                <% end %>
              </li>
              <li class="ml-2">
                <%= link_to logout_path, data: { confirm: "ログアウトしますか?" }, method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>　ログアウト
                <% end %>
              </li>
            </ul>
          </li>
          <li>
            <a class="inline-block ml-3" id="search_form" data-toggle="collapse" href="#search" role="button" aria-expanded="false" aria-controls="search">
              <i class="fas fa-search"></i>                               
            </a>
          </li>
          </ul>
          <div class="collapse" id="search">
            <%= search_form_for @q, url: topics_search_path, class:"form-inline" do |f| %>
             <div class="form-inline">
                <%= f.select :years_id_eq, options_from_collection_for_select(Year.all, :id, :year_number ), include_blank: "学年から探す", class:"form-control mb-0 mr-2" %>
             </div>
             <div class="form-inline">
                <%= f.select :labels_id_eq, options_from_collection_for_select(Label.all, :id, :name ), include_blank: "教科から探す", class:"form-control mb-0 mr-2" %>
            </div>
              <%= f.search_field :description_cont, placeholder: 'キーワードから探す', class:'form-control mb-0' %>
              <%= f.button type: "submit", class:"btn btn-info" do%>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          </div>
 
        <% else %>
          <li class="inline-block"><%= link_to "ログインはこちら", login_path %></li>
        <% end %>
        
     
        
      </ul>
    
    
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
     
</header>

app/views/layouts/_rails.default.html.erb
 <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails.default' %>
    <%= render 'layouts/shim' %>
    <script src="https://kit.fontawesome.com/339e8a6f83.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container user-wrapper">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <% if action_name == "show" %>
        <div data-turbolinks="false">
          <%= link_to :back do %>
            <button type="button" class="btn btn-info">戻る</button>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>

</html>